### ISSUE TITLE
May I ask how to process the raw public detection in this code?

### ISSUE THREAD

**Issue by fandulu** [AndreaHor/LifT_Solver#3]
Thanks for offering the code, I find your detection quality is super good than others, so I download the submission results to compare with the raw public detection, and find the box coordinates are not quite matched. However, in this paper, I did not find how to refine the raw public detection coordinates, but only to remove false positive detection. May I know how to process the raw public detection in this code?

**Comment by RHenschel** [comment]
Hi,
as mentioned in the paper, detections are rejected and refined using the approach presented in the work of tracking without bells and whistles (https://github.com/phil-bergmann/tracking_wo_bnw). 
Basically, you just pass each detection through their pipeline (https://github.com/phil-bergmann/tracking_wo_bnw/blob/master/src/tracktor/frcnn_fpn.py), which applies the head of a F-RCNN detector on the image content of a detection. The head outputs for each detection: (i) a confidence score and (ii) regression parameters. The confidence score is used to reject detections, while the regression parameters are used for the refinement. 

Note that we uploaded the pre-processed input detections for MOT17.

**Comment by fandulu** [comment]
Thanks for replying. Your Recall and Precision of the detection are much higher than the Tracktor can approach, that's my question come from.

**Comment by RHenschel** [comment]
The detections are the directly result of applying Tracktor (but without any linking). You just apply https://github.com/phil-bergmann/tracking_wo_bnw/blob/master/src/tracktor/frcnn_fpn.py to each detection.

**Comment by fandulu** [comment]
Thanks.
