### ISSUE TITLE
Questions about "postprocessing" in tracker/TrackingViaLiftedPath.m

### ISSUE THREAD

**Issue by Monologuethl** [AndreaHor/LifT_Solver#5]
TrackingViaLiftedPath (line 117)
`    trajectoriesAfterPostProcessing = postProcessing(LDPtrajectories,paramsTracking,mot_sequence);`
I did not find the relevant code, may I ask where I can find it？

**Comment by RHenschel** [comment]
The files have been uploaded. Thanks for the hint!
