### ISSUE TITLE
Could I train it on my own data

### ISSUE THREAD

**Issue by nihuo76** [AndreaHor/LifT_Solver#6]
Thank you so much for sharing your work, it's amazing. 
I am trying to train on my own custom dataset. 
Do I need to create my own edge classifier and build my own CNN architecture? Or may I ask if you have any future plan of sharing your APIs on creating graph weights? 
Many thanks~

**Comment by RHenschel** [comment]
Currently we are not planning to release this code but might consider to do so later.

**Comment by nihuo76** [comment]
> Currently we are not planning to release this code but might consider to do so later.

Got it. Many thanks ~

**Comment by liuyvchi** [comment]
Is the code for training available now?

**Comment by RHenschel** [comment]
You can run the solver with your own costs, e.g. similar to explained in the paper.
So far we are not releasing the training code though.
